server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

github:
  username: ${GITHUB_USERNAME:marianamarinflor622}
  token: ${GITHUB_TOKEN:}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - optional:classpath:application-security.yml
  web:
    cors:
      allowed-origins: ${CORS_ORIGINS:http://localhost:5173,https://*.vercel.app}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "Content-Type,Authorization,X-Requested-With,Accept,Origin"
      allow-credentials: true
      max-age: 3600
  mvc:
    problemdetails:
      enabled: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

mail:
  recipient: ${MAIL_RECIPIENT:}